# Change these first
owner: FastGitORG # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: FastGit Home
    url: https://fastgit.org
  - name: FastGit Archive
    url: https://archive.fastgit.org
  - name: FastGit Document
    url: https://doc.fastgit.org
  - name: FastGit Download
    url: https://download.fastgit.org
  - name: FastGit Hub
    url: https://hub.fastgit.org
  - name: FastGit Raw
    url: https://raw.fastgit.org
  - name: FastGit Status
    url: https://status.fastgit.org
  - name: GitHub
    url: https://github.com

assignees: # Users to assign downtime issues (optional)
  - KevinZonda

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://cdn.jsdelivr.net/gh/FastGitORG/logo@ad87e38c7101537010b3dc6f7d4d52bd1f915002/v2.1.png
  name: FastGit Uptime
  introTitle: "**FastGit**, fast way to get GitHub things."
  introMessage: See, we always reach our SLA requirement (0%+)!
  navbar:
    - title: Home
      href: https://fastgit.org
    - title: GitHub
      href: https://github.com/FastGitORG

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
